[tool.poetry]
name = "lep"
version = "1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyquery = "^1.4"

[tool.poetry.dev-dependencies]
ipython = "^7.2"
ipdb = "^0.11.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
